{{- if .Values.vdb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-vdb.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-1"
type: Opaque
stringData:
  database-name: {{ .Values.vdb.database.name | quote }}
  database-user: {{ .Values.vdb.database.user | quote }}
  database-password: {{ .Values.vdb.database.password | quote }}
  connection-string: "postgresql://{{ .Values.vdb.database.user }}:{{ .Values.vdb.database.password }}@{{ .Release.Name }}:{{ .Values.vdb.port }}/{{ .Values.vdb.database.name }}"
  jdbc-url: "jdbc:postgresql://{{ .Release.Name }}:{{ .Values.vdb.port }}/{{ .Values.vdb.database.name }}"
{{- end }}
---
{{- if and .Values.vdb.enabled .Values.service.public }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-public
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-vdb.labels" . | nindent 4 }}
    service-type: public
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  annotations:
    "argocd.argoproj.io/sync-wave": "{{ .Values.syncWave | default "0" }}"
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.vdb.port }}
      targetPort: {{ .Values.vdb.port }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "postgres-vdb.selectorLabels" . | nindent 4 }}
{{- end }}
